[package]
name = "range_bounds_arbitrary"
version = "0.1.0"
authors = ["teor <teor@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proptest = "0.10"